OLED_ENABLE = yes
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
ENCODER_ENABLE = no       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
WPM_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
AUDIO_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAFLAGS += -flto
MIDI_ENABLE = no
UNICODE_ENABLE   = no# Unicode
SWAP_HANDS_ENABLE= no
RAW_ENABLE = yes
CAPS_WORD_ENABLE = yes